### ISSUE TITLE
Doesn't allow empty objects / array

### ISSUE THREAD

**Issue by gotofritz** [jackyjieliu/json-dup-key-validator#1]
Hi. It looks like your validator doesn't like empty objects / arrays

    jsonValidator.validate(`{
      "a": {
        "b": 1
       }
     }`)
    // undefined, as expected

    jsonValidator.validate(`{
      "a": {}
    }  `)
    // Syntax error: expecting String near {}

    jsonValidator.validate(`{
      "a": []
    }  `)
    // Syntax error: expecting String near []

**Comment by jackyjieliu** [comment]
Thanks for reporting this. I will look into it later today

**Comment by jackyjieliu** [comment]
@gotofritz The issue should be fixed now
