### ISSUE TITLE
Doesn't appear to detect duplicate keys

### ISSUE THREAD

**Issue by joetidee** [jackyjieliu/json-dup-key-validator#3]
I have two objects that I convert to JSON before parsing with your function. In both cases the console logs "undefined" - shouldn't the second object throw an error because of the duplicate keys?

```
    let actionsTypeHashValid = {
        table: {
            loading: true,
            data: true,
            query: {
                sort: true,
                limit: true,
                search: true
            }
        }
    };
    console.log(jsonValidator.validate(JSON.stringify(actionsTypeHashValid)));

    let actionsTypeHashInvalid = {
        table: {
            loading: true,
            data: true,
            loading: {
                sort: true,
                limit: true,
                search: true
            }
        },
        table: {
            data: true
        }
    };
    console.log(jsonValidator.validate(JSON.stringify(actionsTypeHashInvalid)));
```

**Comment by jackyjieliu** [comment]
You can not create json objects with duplicated keys in js
```
let actionsTypeHashInvalid = {
        table: {
            loading: true,
            data: true,
            loading: {
                sort: true,
                limit: true,
                search: true
            }
        },
        table: {
            data: true
        }
    };
```
becomes this
```
let actionsTypeHashInvalid = {
        table: {
            data: true
        }
    };
```
if you check the value of actionsTypeHashInvalid after the assignment.

This library is meant to check for duplicated keys in json files because keys would be overwritten if you try to parse a json file with duplicated keys without an error

**Comment by joetidee** [comment]
You're right (slaps head!) - thanks.

**Comment by joetidee** [comment]
So, how do I get this to work? I have placed the following into a .json file:

```
{
  "table": {
    "loading": true,
    "data": true,
    "loading": {
      "sort": true,
      "limit": true,
      "search": true
    }
  },
  "table": {
    "data": true
  }
}
```

then imported it:

```
import jsonfile from 'jsonfile';
let invalidActionTypesHash = jsonfile.readFileSync('./test/invalidActionTypesHash.json');
```

then run through your function:

`console.log(jsonValidator.validate(JSON.stringify(invalidActionTypesHash)));`

result is "undefined"

**Comment by jackyjieliu** [comment]
Hey sorry for the slow response.
You would do `jsonValidator.validate(invalidActionTypesHash)` without the stringify since it is already a string when you read from a file
