### ISSUE TITLE
find a bug !

### ISSUE THREAD

**Issue by Christian-Yang** [jackyjieliu/json-dup-key-validator#4]
I created a file that has a json object。

As long as the key is called "toString" will be an error, suggesting that the key repeat

But if the "toString" change is called another name will not be wrong.、

eg：create a file  called  en.json  ,the add 

{
   "toString":"All"
}
then  the  jso-dup-key-validator  will  show  **Syntax error: duplicated keys "toString" near ring": "Al**

but  there is  only  one  key in the en.json   .

you  can  try  it!!!!

thanks  very much!

oh ,There is another problem here,if the value  is    -1    ,it  will show  as  follow:

[17:24:49] 'build.js.checkJson' errored after 375 ms
[17:24:49] JSON Validate Error in plugin 'gulp-json-validator'
Message:
    Syntax error near ps": -1, 
[17:24:49] 'build.checkJson' errored after 378 ms
[17:24:49] JSON Validate Error in plugin 'run-sequence(build.js.checkJson)'
Message:
    Syntax error near ps": -1,

 the key-->value  ,why  the value  can not be  -1  ???

thank you

**Comment by jackyjieliu** [comment]
Good catch! Thanks for reporting this bug.
It is fixed with https://github.com/jackyjieliu/json-dup-key-validator/pull/5
Let me know if you still have issues with v1.0.2
